---

# Necesitamos el fichero de variables para os_family
- include_vars:
    file: "{{ ansible_facts['os_family'] }}.yml"
    name: "os"

# Instalamos los RPM de tomcat
- name: Instala los RPM de apache
  include_tasks: util/install-package.{{ ansible_facts['os_family'] }}.yml
  vars:
    paquete: "{{ os['softwr_tomcat'] }}"

## Verificamos que el servicio esta arriba
#- name: Verificar el demonio {{ os ['daemon_apache'] }}
#  service:
#    name: "{{ os['daemon_apache'] }}"
#    state: started
#    enabled: yes

# Verificamos que el servicio tomcat esta arrancado
- name: Verificar el demonio tomcat
  service:
    name: tomcat9
    state: started
    enabled: yes

# Copiamos los contenidos que deben mostrar --- cambiar por syncronize (rsync)
- name: Desplegamos la aplicacion sample.war
  copy:
    src: "depot/{{ casa_servicio }}/war/sample.war"
    dest: "{{ os['ctlina_tomcat'] }}" 
    owner: "tomcat"
    group: "tomcat"
    mode: '0640'

- name: Comprueba que la aplicacion sample devuelve un codigo 200
  uri:
    url: "http://{{ inventory_hostname }}:8080/sample"
    status_code: 200

- name: Comprueba que la aplicacion sample devuelve Hello, World
  uri:
    url: "http://{{ inventory_hostname }}:8080/sample"
    return_content: yes
  register: this
  failed_when: "'Hello, World' not in this.content"
